name: Deploy to GitHub Pages

on:
  # å½“æäº¤åˆ° main åˆ†æ”¯æ—¶è§¦å‘
  push:
    branches:
      - main
  # å…è®¸æ‰‹åŠ¨è§¦å‘
  workflow_dispatch:

# è®¾ç½®æƒé™ä»¥å…è®¸æŽ¨é€è‡³åˆ†æ”¯
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

      - name: Setup Bun ðŸ¥Ÿ
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies ðŸ“¥
        run: bun install

      - name: Build ðŸš€
        run: bun run build

      - name: Create CNAME ðŸ“
        run: echo 'word.lovejade.cn' > ./dist/CNAME

      - name: Deploy ðŸš€
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
